<!-- # Preprocessing Tools -->
## What tools are out there?
There are several tools out there that can help in preprocessing raw reads. Most of the preprocessing tools are available via the bioconda channel.
Listed below are some of most common bioinformatics tools used in understanding read features and their quality scores. Click on the hyperlinked tool to learn more on how to install it.

- [Seqkit](https://anaconda.org/bioconda/seqkit/) for simple statistics [@seqkit2016].
- [FastQC](https://anaconda.org/bioconda/fastqc/) for quality assessment of bases [@fastqc2018].
- [MultiQC](https://anaconda.org/bioconda/multiqc/) for summarizing FastQC metrics [@multiqc2016].
- [BBMap](https://anaconda.org/bioconda/bbmap) platform for read trimming and decontamination [@bbmap2016].
- [Trimmommatic](https://anaconda.org/bioconda/trimmomatic/) is a flexible read trimming tool for Illumina NGS data [@trimmomatic2023].
- [Kneaddata](https://anaconda.org/bioconda/kneaddata/) via bioconda channel for performing quality control on metagenomic sequencing data. [@kneaddata2022].
- [Kneaddata](https://anaconda.org/biobakery/kneaddata/) via biobakery channel for performing quality control on metagenomic sequencing data [@kneaddata2022].

> Note that the links for each tool may be outdated. Make sure to check for latest instructions online.

