# config.yaml

# Path to sample sheet (TSV format, columns: sample, condition, ...)
samples: config/samples.tsv

# Path to sequencing unit sheet (TSV format, columns: sample, unit, fq1, fq2)
units: config/units.tsv

# Change these settings before running workflow.


# Auto created from fastq files
dataset: bush
  
# Group names of mock samples (e.g. Mock1_S1_L001_R1_001.fastq.gz = Mock1).
mothurMock:
  - Mock1
  - Mock2
  # - Mock3

# Group names of control samples (e.g. Water1_S2_L001_R1_001.fastq.gz = Water1).
mothurControl:
  - Water1
  - Water2
  - Water3

# Desired alpha diversity metrics.
mothurAlpha:
  - nseqs
  - coverage
  - invsimpson
  - shannon
  - sobs

# Desired beta diversity metrics.
mothurBeta:
  - sharedsobs
  - thetayc
  - braycurtis

# Minimum read threshold for subsampling. Review sample statistics from preprocessing step
subthresh: 100

# NOTE: Leave these settings as is.

# Read numbers
readNum:
  - R1
  - R2

sraNum:
  - 1
  - 2

mothurGroups:
  - sample
  - mock
  - control


# Random seed
seed: 110912
