channels:
  - conda-forge
  - bioconda
  - R
dependencies:
  - r-tidyverse =1.3.2
  - fastqc =0.11.9
  - mothur =1.48.0
  - multiqc =1.14
  - tqdm =4.64.1
  - pysradb =0.6.0
  - trimmomatic =0.39
  - libidn2 =2.3.3
  - libunistring =0.9.10
  - wget =1.20.3
  - mothur =1.48.0
  - vsearch =2.15.2